---
kind: Template
apiVersion: v1
metadata:
  name: timemachine-web-build-template
  creationTimestamp: 
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "${NAME}-${TAG_NAME}"
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: "${NAME}-build-${TAG_NAME}"
    labels:
      app: "${NAME}-build-${TAG_NAME}"
  spec:
    runPolicy: Serial
    source:
      type: Git
      git:
        uri: "${GIT_REPO_URL}"
        ref: "${GIT_REF}"
      contextDir: "${SOURCE_CONTEXT_DIR}"
    strategy:
      type: Docker
    output:
      to:
        kind: ImageStreamTag
        name: "${NAME}-${TAG_NAME}:latest"
parameters:
- name: NAME
  displayName: Name
  description: The name assigned to all of the resources defined in this template.
  required: true
  value: timemachine-web
- name: GIT_REPO_URL
  displayName: Git Repo URL
  description: The URL to your GIT repo.
  required: true
  value: https://github.com/bcgov/Project-and-time-tracker.git
- name: GIT_REF
  displayName: Git Reference
  description: The git reference or branch.
  required: true
  value: master 
- name: SOURCE_CONTEXT_DIR
  displayName: Source Context Directory
  description: The source context directory.
  required: false
  value: openshift/templates/nginx/
- name: TAG_NAME
  displayName: Environment Name
  description: The name of the environment you ultimately wish to deploy to (dev, test, prod)
  required: true
  value: dev
