services:
  api:
    build: api
    ports:
      - "3000:3000"
    container_name: api
    env_file:
      - .env
  web:
    build: web
    ports:
      - "8080:8080"
    links:
      - api
    container_name: web
    env_file:
      - .env