apiVersion: template.openshift.io/v1
kind: Template
metadata:
  labels:
    app: timemachine-web
  name: timemachine-build
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: timemachine-web
    labels:
      app: timemachine-web
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: timemachine-web-${GIT_REF}-build
    labels:
      app: timemachine-web
      name: timemachine-web-${GIT_REF}-build
  spec:
    output:
      to:
        kind: ImageStreamTag 
        name: timemachine-web:${OUTPUT_IMAGE_TAG}
    resources:
      limits:
        cpu: ${CPU_LIMIT}
        memory: ${MEMORY_LIMIT}
      requests:
        cpu: ${CPU_REQUEST}
        memory: ${MEMORY_REQUEST}
    runPolicy: Serial
    source:
      contextDir: ${SOURCE_CONTEXT_DIR}
      git:
        ref: ${GIT_REF}
        uri: ${GIT_REPO_URL}
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: BUILD_LOGLEVEL
          value: "5"
        from:
          kind: ImageStreamTag
          name: ${SOURCE_IMAGE_NAME}:${SOURCE_IMAGE_TAG}
          namespace: ${SOURCE_IMAGE_NAMESPACE}
        incremental: false
      type: Source
    triggers:
    - type: ConfigChange
parameters:
- description: |
    The URL to your GIT repo, don't use the this default unless
    your just experimenting.
  displayName: Git Repo URL
  name: GIT_REPO_URL
  required: true
  value: https://github.com/bcgov/Project-and-time-tracker.git
- description: The git reference or branch.
  displayName: Git Reference
  name: GIT_REF
  required: true
  value: master
- description: The source context directory.
  displayName: Source Context Directory
  name: SOURCE_CONTEXT_DIR
  required: false
  value: "web"
- description: The tag given to the built image.
  displayName: Output Image Tag
  name: OUTPUT_IMAGE_TAG
  required: true
  value: latest
- description: The openshift project where builds and target images are stored.
  displayName: Build Project
  name: SOURCE_IMAGE_NAMESPACE
  value: ed57f0-tools
  required: true
- description: The name of the source image.
  displayName: Source Image Name
  name: SOURCE_IMAGE_NAME
  value: 'caddy-s2i-builder'
  required: true
- description: The tag of the source image.
  displayName: Source Image Tag
  name: SOURCE_IMAGE_TAG
  value: "latest"
  required: true
- description: The resources CPU limit (in cores) for this build.
  displayName: Resources CPU Limit
  name: CPU_LIMIT
  required: true
  value: "2"
- description: The resources Memory limit (in Mi, Gi, etc) for this build.
  displayName: Resources Memory Limit
  name: MEMORY_LIMIT
  required: true
  value: 2Gi
- description: The resources CPU request (in cores) for this build.
  displayName: Resources CPU Request
  name: CPU_REQUEST
  required: true
  value: "1"
- description: The resources Memory request (in Mi, Gi, etc) for this build.
  displayName: Resources Memory Request
  name: MEMORY_REQUEST
  required: true
  value: 2Gi
