---  
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: platsrv-timemachine
    cluster-name: timemachine-patroni
  name: timemachine-patroni
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: platsrv-timemachine
    cluster-name: timemachine-patroni
  name: timemachine-patroni
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get
      - patch
      - update
      - create
      - list
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: platsrv-timemachine
    cluster-name: timemachine-patroni
  name: timemachine-patroni
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: timemachine-patroni
subjects:
  - kind: ServiceAccount
    name: timemachine-patroni
