name: WEB - Deploy to GH Pages

on:
  push:
    paths:
      - 'web/*'
      - '.github/workflows/web.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
      working-directory: ./web
    - run: npm run build --if-present
      working-directory: ./web
    # TEMPORARILY COMMENTED OUT UNTIL TESTS PASS
    # - run: npm run test:unit
    #   working-directory: ./web
    #   env:
    #     CI: true
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.timemachineDeploy}}
        BRANCH: gh-pages
        FOLDER: dist
